# Generated by Django 5.1.1 on 2026-04-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_api', '0003_remove_userfitnessdata_calories_burned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfitnessdata',
            name='activity_level',
            field=models.CharField(default='moderate', max_length=20),
        ),
    ]
