# Generated by Django 6.0.4 on 2026-04-15 10:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_api', '0004_userfitnessdata_activity_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfitnessdata',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'قليل الحركة'), ('light', 'خفيف'), ('moderate', 'متوسط'), ('active', 'نشيط'), ('very_active', 'ناشط جداً')], default='moderate', max_length=20),
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_title', models.CharField(max_length=200)),
                ('plan_json', models.JSONField()),
                ('plan_text', models.TextField()),
                ('difficulty_level', models.CharField(default='beginner', max_length=50)),
                ('duration_weeks', models.IntegerField(default=4)),
                ('equipment_needed', models.TextField(blank=True)),
                ('estimated_time_per_session', models.CharField(default='45-60 دقيقة', max_length=50)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('fitness_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to='fitness_api.userfitnessdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
